version: "3.3"

services:
  tgbot:
    build:
      context: ./
      dockerfile: bot/Dockerfile
    restart: always
    container_name: tgbot
    depends_on:
      - postgres
      - redis
      - migrations
    command: python3 /project/main.py --file=tgbot
  
  migrations:
    build:
      context: ./
      dockerfile: bot/scripts/Dockerfile
    restart: 'no'
    container_name: migrations
    depends_on:
      - postgres
    command: python3 project/bot/scripts/main.py

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    restart: always
    container_name: backend
    depends_on:
      - tgbot
    command: python3 /project/main.py --file=backend

  postgres:
    restart: always
    image: postgres:14.11
    container_name: psql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roma1234
      POSTGRES_DB: postgres
    ports:
      - 5001:5432

  redis:
    restart: always
    image: redis:6.0
    ports:
      - 6001:6379