version: "3.3"

services:
  tgbot:
    build: bot/
    restart: always
    container_name: tgbot
    depends_on:
      - postgres
      - redis
      - migrations
    command: sh -c "sleep 7 && while ! redis-cli -h redis -p 6379 ping; do sleep 5; done 
      && while ! pg_isready -d tgbot -h postgres -p 5432 -U postgres; do sleep 10; done
      && python3 /project/bot/main.py"
  
  migrations:
    build:
      context: ./bot/
      dockerfile: scripts/Dockerfile
    restart: 'no'
    container_name: migrations
    depends_on:
      - postgres
    command: sh -c "while ! pg_isready -h postgres -p 5432; do sleep 5; done 
      && python3 /project/bot/scripts/run_migrations.py"

  postgres:
    restart: always
    image: postgres:14.11
    container_name: psql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roma1234
      POSTGRES_DB: postgres
    ports:
      - 5000:5432

  redis:
    restart: always
    image: redis:6.0
    ports:
      - 6000:6379