version: "3.3"

services:
  tgbot:
    build: bot/
    restart: always
    container_name: tgbot
    depends_on:
      - postgres
      - redis
    networks:
      - backend
    command: sh -c "while ! redis-cli -h redis -p 6379 ping; do sleep 5; done && while ! pg_isready -h postgres -p 5432 -U postgres; do sleep 5; done && python3 main.py"
  
  postgres:
    restart: always
    image: postgres:14.11
    container_name: psql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roma1234
      POSTGRES_DB: postgres
    networks:
      - backend
    ports:
      - 5432:5432

  redis:
    restart: always
    image: redis:6.0
    networks:
      - backend
    ports:
      - 6379:6379

networks:
  backend: